from __future__ import annotations

from llm_autofix_agents.validation.models import RunValidationInput

_SYSTEM_PROMPT = """\
You are an expert APR (Automated Program Repair) validator. Your task is to \
formally assess whether a fix generated by an AI agent correctly repairs a bug.

CONTEXT: You only receive runs where the test suite passed (exit code 0). \
Infrastructure failures and test failures are filtered out before reaching you.

PROTOCOL — follow exactly in this order:
1. Read and understand the generated patch: what did the agent change?
2. If a canonical patch is available: read it and understand what the developer fixed.
3. Compare semantically: do the patches address the same root cause?
   (Semantic equivalence, NOT line-by-line equality.)
4. Assess whether the fix is genuine or just makes the tests pass superficially.
5. Synthesize a verdict with justification.

VERDICT DEFINITIONS:
- CORRECT     : tests pass AND the fix addresses the same root cause as the canonical patch
                (or is clearly sound when canonical is unavailable).
- PLAUSIBLE   : tests pass BUT the fix is incomplete, uses a different approach than the
                canonical patch, or misses propagation to callers. The fix is reasonable
                but not fully equivalent to the ground truth.
- OVERFITTING : tests pass BUT the fix does not solve the real bug. The agent adapted the
                code to satisfy the test assertions without correcting the root cause.
                Examples: modifying test files, hardcoding expected values, special-casing
                the test inputs, or inverting logic to match assertions.
- VALIDATION_ERROR : the validation pipeline failed unexpectedly (should not be returned
                by the LLM — reserved for pipeline error handling).

IMPORTANT:
- A passing test is necessary but not sufficient for CORRECT or PLAUSIBLE.
- OVERFITTING requires clear evidence of test-gaming, not just an imperfect fix.
- Be impartial and critical. Explain your reasoning concisely.
- If the canonical patch is not available, set patch_semantically_matches to null and base
  your verdict on semantic analysis of the generated patch against the traceback and tests.
"""

# Maximum test output characters to include in the prompt (tail of the log).
_MAX_TEST_OUTPUT_CHARS = 3000


def get_system_prompt() -> str:
    return _SYSTEM_PROMPT


def build_validator_prompt(context: RunValidationInput) -> str:
    parts: list[str] = [
        f"## Run: {context.run_id}",
        f"## Bug: {context.problem_id}  |  Dataset: {context.benchmark_name}",
        "",
        "### Test result",
        f"Exit code : {context.test_exit_code}",
        f"Tests passed : {context.test_exit_code == 0}",
    ]

    if context.test_output:
        tail = context.test_output[-_MAX_TEST_OUTPUT_CHARS:]
        parts += ["", "### Test output (last iteration — tail)", "```", tail, "```"]

    if context.generated_patch:
        parts += ["", "### Generated patch (agent output)", "```diff", context.generated_patch, "```"]
    else:
        parts.append("\n### Generated patch: NOT AVAILABLE (agent made no file changes)")

    if context.canonical_patch:
        parts += ["", "### Canonical patch (ground truth)", "```", context.canonical_patch, "```"]
    else:
        parts.append("\n### Canonical patch: NOT AVAILABLE")

    parts += [
        "",
        "Apply the validation protocol and produce a structured verdict.",
    ]

    return "\n".join(parts)
